### PR TITLE
Fix some of landley's concerns (DO NOT MERGE)

### PR DESCRIPTION
**Pull request by gavinhoward**
DO NOT MERGE THIS. Yet.

This PR fixes some of Rob Landley's concerns regarding the bc. I expect to add to this as more concerns come to light (ie, this is a staging area for requested changes).

I found as many style problems as I could with variable declarations and fixed all of them. I also updated my release script to change "bcg." to "TT." which would make this look more like other toys in toybox. I also got rid of the flags that I defined by hand in my repo.

### CODE REVIEW

**Comment by gavinhoward** [comment]
I have made more changes to my copy of toybox. The script should now be in line with landley's copy, with a few differences (to reduce loc). All of these changes were accomplished by using an automated release script.

Also, @landley introduced a logic error when handling command-line argument flags. This PR fixes that.

Again, DO NOT MERGE.

**Comment by landley** [comment]
On 03/12/2018 10:43 PM, Gavin D. Howard wrote:
> I have made more changes to my copy of toybox. The script should now be in line
> with landley's copy, with a few differences (to reduce loc). All of these
> changes were accomplished by using an automated release script.
> 
> Also, @landley <https://github.com/landley> introduced a logic error when
> handling command-line argument flags. This PR fixes that.

Yeah, sorry. I fixed it in the following pass last night (forgot to hit send on
the email until this morning).

Does posting them to the mailing list work for you?

Rob

**Comment by gavinhoward** [comment]
It does. I am working on changes.

**Comment by gavinhoward** [comment]
I have managed to remove some lines of code myself using something that I had intended to do but had missed. However, these changes will not be compatible with you are currently doing. I will attempt to resolve merge conflicts later when you are satisfied.

**Comment by landley** [comment]
On 03/13/2018 02:14 PM, Gavin D. Howard wrote:
> I have managed to remove some lines of code myself using something that I had
> intended to do but had missed. However, these changes will not be compatible
> with you are currently doing. I will attempt to resolve merge conflicts later
> when you are satisfied.

I can just replace what I've got with your update and then redo cleanups on top
of it.

Rob

**Comment by gavinhoward** [comment]
Okay. That's fine too, though I was working on even more changes and a bug fix, if you want them.

**Comment by landley** [comment]
On 03/13/2018 03:15 PM, Gavin D. Howard wrote:
> Okay. That's fine too, though I was working on even more changes and a bug fix,
> if you want them.

Poke me when you've got a resync point.

Rob

**Comment by gavinhoward** [comment]
Poke.

This has been updated to a point where (I think) the only change that you have talked about that **hasn't** been implemented is inlining `bc_vm_init()`. I can revisit that later, but for now, it is outside of what I can do.

A list of things I did:

* Removed all of the globals you removed.
* Inlined `bc_exec()`.
* Removed the globals struct that I missed.
* Removed spurious casts (thanks for that, I actually kept that change in my repo).
* Removed `BC_NUM_ZERO()`, `BC_NUM_NEG_ONE()` and `BC_NUM_POS_ONE()`.
* Removed all references to `unsigned char`.
* Various other style fixes.

I should thank you for using `-funsigned-char` by the way. I did not know about it, and when I was integrating the first attempt, it caused me to find bugs in my math.

**Comment by gavinhoward** [comment]
Per my email to the mailing list, I am closing this to continue working on the bc to make it bulletproof before I submit it for toybox.

**Pull request closed without merging**
