### PR TITLE
lib.[ch]: switch loggit to macro, to avoid non-standard vsyslog

### PR DESCRIPTION
**Pull request by E5ten**

### CODE REVIEW

**Comment by E5ten** [comment]
Related question, is there a reason to keep loggit in lib, given that it's only used in su?

**Comment by landley** [comment]
No.

**Comment by landley** [comment]
I believe the original intent was to have the other users of syslog in pending go through that function? It's been a while. (But function to multiline macro expanding in each caller because posix hasn't caught up to reality is not a compelling change. What's it "portable" _to_?)

**Comment by E5ten** [comment]
Fair enough, multiline macros are not ideal.

**Pull request closed without merging**
