### PR TITLE
WIP: add -t to cp, mv, and install

### PR DESCRIPTION
**Pull request by E5ten**
I expect there will be issues within this, that said I did not find any immediately that I didn't fix before committing and I figured getting a WIP PR up would be the best way to expose further problems. In terms of use cases:
https://github.com/archlinux/mkinitcpio/blob/master/Makefile this uses cp -t
https://git.archlinux.org/svntogit/packages.git/tree/trunk/PKGBUILD?h=packages/linux and this uses both cp -t and install -t. I have not seen mv -t used, but saw no reason to leave it out for mv alone since GNU mv has it.

### CODE REVIEW

**Comment by landley** [comment]
I'm confused... what changed? (The diff of the 149.patch I downloaded earlier and the 149.patch I just downloaded is... large.)

**Comment by landley** [comment]
Is it just me or does:

+USE_MV(NEWTOY(mv, "<1t:vnF(remove-destination)fit:[-ni]", TOYFLAG_BIN))

Have t: in it twice?

**Comment by landley** [comment]
+  if (!toys.optc && !TT.t) error_exit("needs 2 args");

So if you say "cp" by itself it'll say "Needs 1 argument", and then if you go "cp file" it'll say "needs 2 args" with no explanation, and different phrasing and capitalization. The current lib/args.c output is:

$ toybox cp blah
cp: Need 2 arguments (see "cp --help")

(Which comes from help_exit() rather than error_exit().)

Rob

P.S. There's a reason I generally do this stuff on the mailing list. You're gonna get a lot of short emails from this...

**Comment by enh-google** [comment]
3d5cb06e8b5cfcd4226375ff435b1725399fda13 adds -t to install, but not cp/mv.

**Comment by landley** [comment]
Commit 6d615c73b321 then.

**Pull request closed without merging**
