### PR TITLE
Replace [gs]ettimeofday with clock_[gs]ettime

### PR DESCRIPTION
**Pull request by E5ten**
gettimeofday is XSI, not POSIX, and is marked obsolete, while settimeofday is non-standard. Switch use of these functions to their modern replacements.

### CODE REVIEW

**Comment by E5ten** [comment]
In addition to musl ignoring the settimeofday timezone argument, mentioned in the hwclock commit, glibc 2.31 and up apparently errors when settimeofday is called with both arguments non-NULL.

**Comment by landley** [comment]
Six patches in one pull request.

**Comment by E5ten** [comment]
Sorry about that, I'll split them up.

**Comment by E5ten** [comment]
Made a new PR for each command changed, closing this one.

**Pull request closed without merging**
