### PR TITLE
Fix install -t

### LINKED ISSUE #270: install -D -t <dir> does not create <dir>
This also doesn't work with `install -D file1 file2 dir`, where dir doesn't exist, but busybox also messes that up (differently, instead of making dir and putting file[12] there, it makes dir's parents and makes puts file2 as dir) so I'm not sure what should be done in that situation.
Either way, with any install I've seen that has `-t`, it creates the dir given to `-t` when `-D` is also passed.

### PR DESCRIPTION
**Pull request by E5ten**
I ran the tests with this and saw no regressions, and it seems to fix #270

### CODE REVIEW

**Comment by landley** [comment]
Could you add a tests/install.test entry demonstrating what it fixes?

(Due to the name conflict with "make install" there's no make test_install target, you have to run "scripts/test.sh install" directly. It's run as part of "make tests" though.)

**Comment by E5ten** [comment]
Done, let me know if there's anything wrong with the test case, I think that's the first one I've written for toybox.

**Comment by E5ten** [comment]
Also, in regards to the name conflict, I think the usual strategy here is to use xinstall throughout the source (like for the test name, the make target, etc.) and then to just install xinstall as install for `make install`. No idea how plausible or desirable it is to do something like this for toybox, but figured I'd bring it up in case it's a workable solution for the inability to run `test_install` individually.

**Comment by E5ten** [comment]
Closed by https://github.com/landley/toybox/commit/3cde24138ac06e384965db2944e858d2110ecacb

**Pull request closed without merging**
